### ISSUE TITLE
Dashboard: Back button doesn't do what you think

### ISSUE THREAD

**Issue by jszasz** [mctaggaj/SolidArc_AdminPortal#2]
Type: Enhancement - doesn't break our product, just annoying
Priority: Medium - users could notice it and get annoyed

Pre: You are on the administrator dashboard, and you click a category, and then click a operation, and get brought to that operation page.

Issue: When you press the back button, you should be brought to the previous page you were on (the category you clicked), but you get brought back to the main dashboard. 

Fix: Make the back button load the category you were on.

**Comment by jszasz** [comment]
It seems to be working on EVENTS but not on TEAMS.

Double check that it works on all.

**Comment by mctaggaj** [comment]
This is strange.. I'll look into it more.

**Comment by mctaggaj** [comment]
Fixed in commit 9f2ac8faea0de8d93a57def804dc415559c0bfbd
